Find the default global Firefox install on Mac OSX automatically

diff --git a/src/slimerjs b/src/slimerjs
--- a/src/slimerjs
+++ b/src/slimerjs
@@ -31,14 +31,20 @@ then
         then
             SLIMERJSLAUNCHER="$SLIMERDIR/xulrunner/xulrunner.exe"
         else
-            SLIMERJSLAUNCHER=`command -v firefox`
-            if [ "$SLIMERJSLAUNCHER" == "" ]
+            # Try the Mac OSX global default application path
+            if [ -f "/Applications/Firefox.app/Contents/MacOS/firefox" ]
             then
-                SLIMERJSLAUNCHER=`command -v xulrunner`
+                SLIMERJSLAUNCHER="/Applications/Firefox.app/Contents/MacOS/firefox"
+            else
+                SLIMERJSLAUNCHER=`command -v firefox`
                 if [ "$SLIMERJSLAUNCHER" == "" ]
                 then
-                    echo "SLIMERJSLAUNCHER environment variable is missing. Set it with the path to Firefox or XulRunner"
-                    exit 1
+                    SLIMERJSLAUNCHER=`command -v xulrunner`
+                    if [ "$SLIMERJSLAUNCHER" == "" ]
+                    then
+                        echo "SLIMERJSLAUNCHER environment variable is missing. Set it with the path to Firefox or XulRunner"
+                        exit 1
+                    fi
                 fi
             fi
         fi
