SlimerJS is now packaged with XulRunner

diff --git a/src/slimerjs b/src/slimerjs
--- a/src/slimerjs
+++ b/src/slimerjs
@@ -1,15 +1,37 @@
 #!/bin/bash
 
+#retrieve full path of the current script
+# symlinks are resolved, so application.ini could be found
+# this code comes from http://stackoverflow.com/questions/59895/
+SOURCE="${BASH_SOURCE[0]}"
+while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
+  SLIMERDIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
+  SOURCE="$(readlink "$SOURCE")"
+  [[ $SOURCE != /* ]] && SOURCE="$SLIMERDIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
+done
+SLIMERDIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
+
+# retrieve the path of a gecko launcher
 if [ "$SLIMERJSLAUNCHER" == "" ]
 then
-    SLIMERJSLAUNCHER=`command -v firefox`
-    if [ "$SLIMERJSLAUNCHER" == "" ]
+    if [ -f "$SLIMERDIR/xulrunner/xulrunner" ]
     then
-        SLIMERJSLAUNCHER=`command -v xulrunner`
-        if [ "$SLIMERJSLAUNCHER" == "" ]
+        SLIMERJSLAUNCHER="$SLIMERDIR/xulrunner/xulrunner"
+    else
+        if [ -f "$SLIMERDIR/xulrunner/xulrunner.exe" ]
         then
-            echo "SLIMERJSLAUNCHER environment variable is missing. Set it with the path to Firefox or XulRunner"
-            exit 1
+            SLIMERJSLAUNCHER="$SLIMERDIR/xulrunner/xulrunner.exe"
+        else
+            SLIMERJSLAUNCHER=`command -v firefox`
+            if [ "$SLIMERJSLAUNCHER" == "" ]
+            then
+                SLIMERJSLAUNCHER=`command -v xulrunner`
+                if [ "$SLIMERJSLAUNCHER" == "" ]
+                then
+                    echo "SLIMERJSLAUNCHER environment variable is missing. Set it with the path to Firefox or XulRunner"
+                    exit 1
+                fi
+            fi
         fi
     fi
 fi
@@ -22,7 +44,6 @@ fi
 
 function showHelp() {
 
-    #echo "  --cookies-file=<file>              Sets the file name to store the persistent"
     #echo "                                     cookies."
     #echo "  --config=<file>                    Load the given configuration file"
     #echo "                                     (JSON formated)"
@@ -31,9 +52,7 @@ function showHelp() {
     #echo "  --disk-cache=[yes|no]              Enables disk cache (default is no)."
     echo "  --help or -h                       Show this help"
     #echo "  --ignore-ssl-errors=[yes|no]       Ignores SSL errors (default is no)."
-    #echo "  --load-images=[yes|no]             Loads all inlined images (default is yes)"
-    #echo "  --local-storage-path=<path>        Specifies the location for offline local"
-    #echo "                                     storage"
+    echo "  --load-images=[yes|no]             Loads all inlined images (default is yes)"
     #echo "  --local-storage-quota=<number>     Sets the maximum size of the offline"
     #echo "                                     local storage (in KB)"
     #echo "  --local-to-remote-url-access=[yes|no] Allows local content to access remote"
@@ -53,7 +72,6 @@ function showHelp() {
     #echo "                                     script (default is utf8)"
     #echo "  --web-security=[yes|no]            Enables web security (default is yes)"
     #echo "  --ssl-protocol=[SSLv3|SSLv2|TLSv1|any]  Sets the SSL protocol"
-    #echo "  --ssl-certificates-path=<path>     Sets the location for custom CA certificates"
     echo "  --version or v                     Prints out SlimerJS version"
     #echo "  --webdriver or --wd or -w          Starts in 'Remote WebDriver mode' (embedded"
     #echo "                                     GhostDriver) '127.0.0.1:8910'"
@@ -79,17 +97,6 @@ function showHelp() {
     echo "By default, SlimerJS use a temporary profile"
     echo ""
 }
-
-#retrieve full path of the current script
-# symlinks are resolved, so application.ini could be found
-# this code comes from http://stackoverflow.com/questions/59895/
-SOURCE="${BASH_SOURCE[0]}"
-while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
-  SCRIPTDIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
-  SOURCE="$(readlink "$SOURCE")"
-  [[ $SOURCE != /* ]] && SOURCE="$SCRIPTDIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
-done
-SCRIPTDIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
 
 # retrieve list of existing environment variable, because Mozilla doesn't provide an API to get this
 # list
@@ -124,7 +131,7 @@ PROFILE=""
 PROFILE_DIR=""
 if [ "$CREATE_TEMP" == "Y" ]
 then
-    PROFILE_DIR=`mktemp -d -q`
+    PROFILE_DIR=`mktemp -d -q /tmp/slimerjs.XXXXXXXX`
     if [ "$PROFILE_DIR" == "" ]; then
         echo "Error: cannot generate temp profile"
         exit 1
@@ -139,7 +146,7 @@ fi
 export __SLIMER_ARGS="$@"
 
 # launch slimerjs with firefox/xulrunner
-"$SLIMERJSLAUNCHER" -app $SCRIPTDIR/application.ini $PROFILE -no-remote --envs "$LISTVAR" "$@"
+"$SLIMERJSLAUNCHER" -app $SLIMERDIR/application.ini $PROFILE -no-remote --envs "$LISTVAR" "$@"
 
 EXITCODE=$?
 
